// Code generated by mapperx, PLEASE DO NOT EVER EDIT. GENERATATED AT 2021-11-06T19:09:34Z
package mapperx

import model "github.com/MrWormHole/mapperx/examples/model"

func AdminToUser(admin *model.Admin, user *model.User) {
	user.Name = admin.Name
	user.ID = admin.ID
	user.Country = admin.Country
	user.Highscore = admin.Score
	user.Friends = make([]string, len(admin.Friends))
	copy(user.Friends, admin.Friends)
	user.GivenPermissions = make(map[string]string, len(admin.Permissions))
	for k, v := range admin.Permissions {
		user.GivenPermissions[k] = v
	}
	user.Minion = admin.Minion
}
